# -*- coding: utf-8 -*-
import sys
reload(sys)
sys.setdefaultencoding("utf-8")

slot2 = {
    "map4": {
        "spreadsheetId_scence": "16i_V-NmIhIqxFyD8HgeNucV70DYoE3iqjyD3fpqNXkI",
        "rangeName_scence": "Timeline!D2:BK34",
        "rangeName_scence2": "Timeline!D1:BK34",
        "spreadsheetId": "1mm-sURsigZ3Q_gLgU3RzP14BhljqgyiWED6rPaEM6qI",
        "rangeName": "第一稿-关卡设计!BO5:GM64",
        "foodName": "食物!B3:B60",
        "foodrange": "food!E4:E57",
        "food": "food!B4:B57",
        "upgrade_id": "Upgrade!B4:B93",
        "upgrade_tragetads": "Upgrade!H4:H93",
        "level_guide": "Level!A4:I63",  # slot2 slot4都是63行，只有60关
        "foodg_uide": "Food!A4:F57",
        "col_food": "5",
        "col_level": "8"
    },
    "map3": {
        "spreadsheetId_scence": "1_zKvv9zotGnuJj0KscltwqaM_lUU_987ihbFlN8oevo",
        "rangeName_scence": "Timeline-c!D2:BK32",
        "rangeName_scence2": "Timeline-c!D1:BK34",
        "spreadsheetId": "1pFQNMChfSSqV1vMCEjM8mw7fqViKd03TseTMs4Mnp-I",
        "rangeName": "第一稿-关卡设计!CE5:HC64",
        "foodName": "食物!B3:B47",
        "foodrange": "food!E4:E42",
        "food": "food!B4:B42",
        "upgrade_id": "Upgrade!B4:B90",
        "upgrade_tragetads": "Upgrade!H4:H90",
        "level_guide": "Level!A4:I63",
        "foodg_uide": "Food!A4:F42",
        "col_food": "5",
        "col_level": "8"
    },
    "map2": {
        "spreadsheetId_scence": "16HsFF7iy6w88lUSIUesHes6MYZYEnq4Wy7J-L8z3qTo",
        "rangeName_scence": "Timeline-c!D2:BK29",
        "rangeName_scence2": "Timeline-c!D1:BK34",
        "spreadsheetId": "1SmQNevKYlJzJht8gsnhA29CC74Qav35TDALVf4_zFKI",
        "rangeName": "第一稿-关卡设计!CN5:GR64",
        "foodName": "食物!B3:B47",
        "foodrange": "food!E4:E42",
        "food": "food!B4:B42",
        "upgrade_id": "Upgrade!B4:B81",
        "upgrade_tragetads": "Upgrade!H4:H81",
        "level_guide": "Level!A4:I63",
        "foodg_uide": "Food!A4:F42",
        "col_food": "5",
        "col_level": "8"
    },
    "map1": {
        "spreadsheetId_scence": "1JzGhU8JBgBx47IZ7DXPhb4sUZnly1t-OSqGQCNmna9E",
        "rangeName_scence": "Timeline-d!D2:BK29",
        "rangeName_scence2": "Timeline-d!D1:BK34",
        "spreadsheetId": "1NY4V8naN-LsnkBELWHyPerBOarBg3VSev6ahMBct7iY",
        "rangeName": "第一稿-关卡设计!BQ5:FU64",
        "foodName": "食物!B3:B47",
        "foodrange": "food!E4:E36",
        "food": "food!B4:B36",
        "upgrade_id": "Upgrade!B4:B83",
        "upgrade_tragetads": "Upgrade!H4:H83",
        "level_guide": "Level!A4:I63",
        "foodg_uide": "Food!A4:F39",
        "col_food": "5",
        "col_level": "8"
    },
    "map5": {
        "spreadsheetId_scence": "1zsRwqwAcM22ilYvdyNic-ynlXbD4oZm0RmmPCLO1n-Q",
        "rangeName_scence": "Timeline!D2:BK34",
        "rangeName_scence2": "Timeline!D1:BK34",
        "spreadsheetId": "1LoeZRPrPnJWkjNtM74COVTdV3n6kpUtqo1GZ60RNl9c",
        "rangeName": "第一稿-关卡设计!BJ5:GH64",
        "foodName": "食物!B3:B36",
        "foodrange": "food!E4:E40",
        "food": "food!B4:B40",
        "upgrade_id": "Upgrade!B4:B85",
        "upgrade_tragetads": "Upgrade!H4:H85",
        "level_guide": "Level!A4:I63",
        "foodg_uide": "Food!A4:F40",
        "col_food": "5",
        "col_level": "8"
    }
}

slot4 = {
    "map5": {
        "spreadsheetId_scence": "1lr-eHwwRN1A567hRlZmuiTx7zU6QBf-AB9o1sX0DPa8",
        "rangeName_scence": "Timeline!D2:BK34",
        "rangeName_scence2": "Timeline!D1:BK34",
        "spreadsheetId": "1LoeZRPrPnJWkjNtM74COVTdV3n6kpUtqo1GZ60RNl9c",
        "rangeName": "第一稿-关卡设计!BJ5:GH64",
        "foodName": "食物!B3:B36",
        "foodrange": "food!E4:E40",
        "food": "food!B4:B40",
        "upgrade_id": "Upgrade!B4:B85",
        "upgrade_tragetads": "Upgrade!H4:H85",
        "level_guide": "Level!A4:I63",
        "foodg_uide": "Food!A4:F40",
        "col_food": "5",
        "col_level": "8"
    },
    "map4": {
        "spreadsheetId_scence": "1HO9ZA93QW-jZBlhLSgF_IKwqBbIpBa1TJURQ1vaULBU",
        "rangeName_scence": "Timeline!D2:BK33",
        "rangeName_scence2": "Timeline!D1:BK34",
        "spreadsheetId": "1v-eAQHSLTcj2u_msdtkedBB4wrj0uIVVi1e-tKZMeFI",
        "rangeName": "第一稿-关卡设计!BO5:GM64",
        "foodName": "食物!B3:B50",
        "foodrange": "food!E4:E57",
        "food": "food!B4:B57",
        "upgrade_id": "Upgrade!B4:B92",
        "upgrade_tragetads": "Upgrade!H4:H92",
        "level_guide": "Level!A4:I63",
        "foodg_uide": "Food!A4:F57",
        "col_food": "5",
        "col_level": "8"
    },
    "map3": {
        "spreadsheetId_scence": "11SzQ6trYp1DK86z-ktRT0ANr76fmdPiyng5Ts_ICcHU",
        "rangeName_scence": "Timeline!D2:BK33",
        "rangeName_scence2": "Timeline!D1:BK34",
        "spreadsheetId": "1DfqZ5v20o7jgKKP9HQR2k6OnqP10i5B93MpoqD3T10s",
        "rangeName": "第一稿-关卡设计!CE5:HC64",
        "foodName": "食物!B3:B47",
        "foodrange": "food!E4:E42",
        "food": "food!B4:B42",
        "upgrade_id": "Upgrade!B4:B90",
        "upgrade_tragetads": "Upgrade!H4:H90",
        "level_guide": "Level!A4:I63",
        "foodg_uide": "Food!A4:F42",
        "col_food": "5",
        "col_level": "8"
    },
    "map2": {
        "spreadsheetId_scence": "1n8FjPc78y6TjNmexwVZFBtMqHcGCwTwv99Khw6TLthE",
        "rangeName_scence": "Timeline!D2:BK33",
        "rangeName_scence2": "Timeline!D1:BK34",
        "spreadsheetId": "1lPXokBK3zI8fz_swSBAOa0QRyEX32ypX3PDe7IAyn4g",
        "rangeName": "第一稿-关卡设计!CN5:GR64",
        "foodName": "食物!B3:B47",
        "foodrange": "food!E4:E42",
        "food": "food!B4:B42",
        "upgrade_id": "Upgrade!B4:B93",
        "upgrade_tragetads": "Upgrade!H4:H93",
        "level_guide": "Level!A4:I63",
        "foodg_uide": "Food!A4:F42",
        "col_food": "5",
        "col_level": "8"
    },
    "map1": {
        "spreadsheetId_scence": "1jcZfcQn823qbn3XlcuZJJOa0fkZFOXwssYzAJc_M4F8",
        "rangeName_scence": "Timeline!D2:BK33",
        "rangeName_scence2": "Timeline!D1:BK34",
        "spreadsheetId": "1tOnLTdR_m94ioN0xjQsmtVKvAxOpULMKytUucbj4-D0",
        "rangeName": "第一稿-关卡设计!BQ5:FU64",
        "foodName": "食物!B3:B47",
        "foodrange": "food!E4:E36",
        "food": "food!B4:B36",
        "upgrade_id": "Upgrade!B4:B94",
        "upgrade_tragetads": "Upgrade!H4:H94",
        "level_guide": "Level!A4:I63",
        "foodg_uide": "Food!A4:F36",
        "col_food": "5",
        "col_level": "8"
    }
}


slot5 = {
    "map1": {
        "spreadsheetId_scence": "1n9AXYsYl6p7aEKAsoAGob3KB2Pe4GSw7a4JW8FHqPFY",
        "rangeName_scence": "Timeline!D2:BK34",
        "rangeName_scence2": "Timeline!D1:BK34",
        "spreadsheetId": "1RXP105cQOOJ8aIFRyg2r0H4EPWHAGILCSZjhir9S87k",
        "rangeName": "1-1关卡!BA4:DM63",
        "foodName": "1-1厨房!B3:B13",
        "foodrange": "food!E4:E25",
        "food": "food!B4:B25",
        "foodtype": "food!D4:D26",
        "upgrade_id": "Upgrade!B4:B30",
        "upgrade_tragetads": "Upgrade!H4:H30",
        "level_type": "Level!H4:I93",
        "level_istime": "Level!J4:J93",
        "level_guide": "Level!A4:O63",
        "foodg_uide": "Food!A4:F36",
        "col_food": "5",
        "col_level": "14"
    },
    "map2": {
        "spreadsheetId_scence": "1xlQhdpumr0NIVBqJwbTne-KRJqioa1PZbDCdKcRfCCE",
        "rangeName_scence": "Timeline!D2:CO34",
        "rangeName_scence2": "Timeline!D1:CO34",
        "spreadsheetId": "1RXP105cQOOJ8aIFRyg2r0H4EPWHAGILCSZjhir9S87k",
        "rangeName": "1-2关卡!BN4:ET93",
        "foodName": "1-2厨房!B3:B17",
        "foodrange": "food!E4:E26",
        "foodtype": "food!D4:D26",
        "food": "food!B4:B26",
        "upgrade_id": "Upgrade!B4:B48",
        "upgrade_tragetads": "Upgrade!H4:H48",
        "level_type": "Level!H4:I93",
        "level_istime": "Level!J4:J93",
        "level_guide": "Level!A4:O93",
        "foodg_uide": "Food!A4:F26",
        "col_food": "5",
        "col_level": "14"
    },
    "map3": {
        "spreadsheetId_scence": "1MXwj8MW-HOWHSAIRxocDnxi8Met5NZLSR35dFBmMFps",
        "rangeName_scence": "Timeline!D2:DS34",
        "rangeName_scence2": "Timeline!D1:DS34",
        "spreadsheetId": "1RXP105cQOOJ8aIFRyg2r0H4EPWHAGILCSZjhir9S87k",
        "rangeName": "1-3关卡!BP4:EZ123",
        "foodName": "1-3厨房!B3:B17",
        "foodrange": "food!E4:E23",
        "food": "food!B4:B23",
        "foodtype": "food!D4:D23",
        "upgrade_id": "Upgrade!B4:B48",
        "upgrade_tragetads": "Upgrade!H4:H48",
        "level_type": "Level!H4:I123",
        "level_istime": "Level!J4:J123",
        "level_guide": "Level!A4:Q123",
        "foodg_uide": "Food!A4:F23",
        "col_food": "5",
        "col_level": "16"
    },
    "map4": {
        "spreadsheetId_scence": "1LN6u4NGewf-BYSFVZaDCS46ugI6vncE-ip3zbyWQ5Ns",
        "rangeName_scence": "Timeline!D2:DS28",
        "rangeName_scence2": "Timeline!D1:DS28",
        "spreadsheetId": "1RXP105cQOOJ8aIFRyg2r0H4EPWHAGILCSZjhir9S87k",
        "rangeName": "1-4关卡!BN4:FN123",
        "foodName": "1-4厨房!B3:B14",
        "foodrange": "food!E4:E20",
        "food": "food!B4:B20",
        "foodtype": "food!D4:D20",
        "upgrade_id": "Upgrade!B4:B48",
        "upgrade_tragetads": "Upgrade!H4:H48",
        "level_type": "Level!H4:I123",
        "level_istime": "Level!J4:J123",
        "level_guide": "Level!A4:Q123",
        "foodg_uide": "Food!A4:F20",
        "col_food": "5",
        "col_level": "16"
    },
    "map5": {
        "spreadsheetId_scence": "1dBB7ZXsylRv0FZ5hPgq8h03-O9Nlr8P8dcGxgUHCxm0",
        "rangeName_scence": "Timeline!D2:DS27",
        "rangeName_scence2": "Timeline!D1:DS27",
        "spreadsheetId": "1BKDZltchBPfeUvzof6OpepKusE3Uwmbvg-b24gJfNqs",
        "rangeName": "2-1关卡!BJ4:FF123",
        "foodName": "2-1厨房!B3:B17",
        "foodrange": "food!E4:E22",
        "food": "food!B4:B22",
        "foodtype": "food!D4:D22",
        "upgrade_id": "Upgrade!B4:B39",
        "upgrade_tragetads": "Upgrade!H4:H39",
        "level_type": "Level!H4:I123",
        "level_istime": "Level!J4:J123",
        "level_guide": "Level!A4:Q123",
        "foodg_uide": "Food!A4:F22",
        "col_food": "5",
        "col_level": "16"
    },
    "map6": {
        "spreadsheetId_scence": "167uE0PaDtYp-BhuWR8P-IXW9Sm2wkQlYVPTfzLE-gvo",#map表
        "rangeName_scence": "Timeline!D2:DS23",
        "rangeName_scence2": "Timeline!D1:DS23",
        "spreadsheetId": "1BKDZltchBPfeUvzof6OpepKusE3Uwmbvg-b24gJfNqs",#设计表
        "rangeName": "2-2关卡!BN4:ET123",#第1关菜价开始
        "foodName": "2-2厨房!B3:B18",
        "foodrange": "food!E4:E23",
        "food": "food!B4:B23",
        "foodtype": "food!D4:D23",
        "upgrade_id": "Upgrade!B4:B45",
        "upgrade_tragetads": "Upgrade!H4:H45",
        "level_type": "Level!I4:J123",
        "level_istime": "Level!k4:k123",
        "level_guide": "Level!A4:R123",
        "foodg_uide": "Food!A4:F23",
        "col_food": "5",
        "col_level": "17"
    },
    "map7": {
        "spreadsheetId_scence": "1qoFIglHU5gMT2z0puEPlRAubuGl_sxI1cqBV2vbguLQ",#map表
        "rangeName_scence": "Timeline!D2:DS25",
        "rangeName_scence2": "Timeline!D1:DS25",
        "spreadsheetId": "1BKDZltchBPfeUvzof6OpepKusE3Uwmbvg-b24gJfNqs",#设计表
        "rangeName": "2-3关卡!BZ4:FF123",#第1关菜价开始
        "foodName": "2-3厨房!B3:B24",
        "foodrange": "food!E4:E33",
        "food": "food!B4:B33",
        "foodtype": "food!D4:D33",
        "upgrade_id": "Upgrade!B4:B45",
        "upgrade_tragetads": "Upgrade!H4:H45",
        "level_type": "Level!i4:j123",
        "level_istime": "Level!k4:k123",
        "level_guide": "Level!A4:R123",
        "foodg_uide": "Food!A4:F33",
        "col_food": "5",
        "col_level": "17"
    }
}
